### ISSUE TITLE
Invalid device ordinal

### ISSUE THREAD

**Issue by ahaemhumright** [xiexh20/CHORE#3]
Hi.
Thanks for the great work. I'm trying to test your code on my own data. Unfortunately, I met an error when I run the demo.py, as shown below.
![image](https://user-images.githubusercontent.com/103309109/207045756-37450bd9-2c91-463c-948f-77d646223214.png)
My environment is nvidia RTX 3090ti with cuda 11.3 and pytorch 1.10. 
I am wondering whether it is a cuda version problem and if it is, can this code run on RTX 30xx device (Since RTX 3090ti could only fit cuda version 11+)?

Thank you.

**Comment by xiexh20** [comment]
Hi,

I did not try RTX30xx devices but I think the env should work with cuda 11.0, but with a lower torch version.
Maybe you can try to reinstall the mesh intersection lib with a torch of 1.6/1.7?

Best,

**Comment by lnykyks** [comment]
Hi,
It seems that the mesh intersection lib doesn't work well with torch1.7 and cuda11.0

**Comment by jellyheadandrew** [comment]
I tried torch1.11.0+cu113. Works for me

**Comment by lnykyks** [comment]
@jellyheadandrew what's your gpu configuration

**Comment by jellyheadandrew** [comment]
I used RTX3090
